In [2]:
import pandas
import numpy
import sklearn

print("All important libraries are working!")

All important libraries are working!

In [3]:
import pandas as pd

# Load datasets
fake_df = pd.read_csv("../data/Fake.csv")
true_df = pd.read_csv("../data/True.csv")

print("Fake news samples:", fake_df.shape)
print("Real news samples:", true_df.shape)

fake_df.head()

Fake news samples: (23481, 4)
Real news samples: (21417, 4)

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [4]:
true_df.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [5]:
fake_df["label"] = 0   # 0 = Fake
true_df["label"] = 1   # 1 = Real

In [6]:
df = pd.concat([fake_df, true_df])
df = df.sample(frac=1).reset_index(drop=True)   # shuffle

df.head()

,title,text,subject,date,label
0,"Donald Trump is a problem for the whole world,...",BERLIN (Reuters) - If U.S. Republican presiden...,politicsNews,"September 15, 2016",1
1,"Germans most afraid of terrorism, secure about...","BERLIN (Reuters) - Fear of terrorism, politica...",worldnews,"September 7, 2017",1
2,Rabid Conservatives Blame Obama After Fox Rep...,"According to Fox News viewers, that dastardly ...",News,"April 22, 2016",0
3,"India, at U.N., calls Pakistan 'pre-eminent ex...",UNITED NATIONS (Reuters) - India responded wit...,worldnews,"September 23, 2017",1
4,White House disputes multiple calls between Tr...,WASHINGTON (Reuters) - The White House said on...,politicsNews,"January 23, 2017",1

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44898 entries, 0 to 44897
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    44898 non-null  object
 1   text     44898 non-null  object
 2   subject  44898 non-null  object
 3   date     44898 non-null  object
 4   label    44898 non-null  int64
dtypes: int64(1), object(4)
memory usage: 1.7+ MB

In [8]:
df["label"].value_counts()

label
0    23481
1    21417
Name: count, dtype: int64

In [9]:
df["text"][0]

'BERLIN (Reuters) - If U.S. Republican presidential candidate Donald Trump wins the election in November, it would be problematic for the entire world and encourage copycats in Europe, European Parliament President Martin Schulz told a German magazine. “Trump is not only a problem for the EU but also for the whole world,” Schulz said in an interview with Der Spiegel published online on Thursday. “If a man who shows off by not having a clue and by saying that specialist knowledge is elitist rubbish ends up in the White House, a critical point will have been reached,” said Schulz, a German center-left Social Democrat. Such a scenario would mean that there is an “obviously irresponsible man” sitting in a position that demands the utmost sense of responsibility, Schulz said. He added that he was concerned that Trump getting into power would spur on copycats in Europe. “That’s why I want Hillary Clinton to win.” '

In [10]:
df.to_csv("../data/news_dataset.csv", index=False)
print("Combined dataset saved successfully!")

Combined dataset saved successfully!